title: Unofficial NameMC API Docs
url: https://shrieked.github.io/Unofficial-NameMC-API-Docs/
remote_theme: "mmistakes/minimal-mistakes@4.22.0

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
